import Head from 'next/head';

import { indigo } from '@mui/material/colors';
import Typography from '@mui/material/Typography';

export default function Home() {
  return (
    <>
      <Head>
        <title>FK Store</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Typography variant='h4' textAlign='center'>
        Welcome to <span style={{ color: indigo[500] }}>FK Store!</span>
      </Typography>
    </>
  );
}
